postgres:
  image: mdillon/postgis
  ports:
    - "5597:5432"
  volumes_from:
    - pgdata
  environment:
    POSTGRES_USER: db
    POSTGRES_PASS: db
    POSTGRES_DB: wigs_dev

pgdata:
  image: busybox
  volumes:
    - /data
